<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>IoCManager</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\IoC.Roslyn\IoC.Roslyn.csproj" />
	</ItemGroup>

</Project>
